# Generated by Django 4.2.13 on 2024-10-20 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0005_address_alter_book_author_author_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='book_outlet.address'),
        ),
    ]
